### ISSUE TITLE
Possibility of having any malware in this firmware?

### ISSUE THREAD

**Issue by trickplastic** [wgwoods/gk64-python#3]
I really appreciate your work.

How is the chance of having any malware in this firmware? Have you noticed anything unusual?

Thanks.

**Comment by wgwoods** [comment]
In general, it's pretty hard to tell the difference between code that's just weird or sloppy, and code that's _maliciously_ weird, so take this with a grain of salt, but: I personally didn't find anything that struck me as malicious or worrying. 

To give a little more detail: I was digging into the firmware because I wanted to see if I could find out a) what it's doing with audio from the microphone, and b) whether it's logging keystrokes or anything like that, and everything I found seems pretty innocuous.

I'm pretty sure I found most of the code that handles the audio input / audio-reactive lighting effects, and I didn't see anything that looks like it saving audio data. The processing it's doing is very simple and the buffers look too small to do any actual recording. It also doesn't seem to send any of that data to the host system - there's a surprising amount of USB traffic with their drivers running, but I don't think any of it's audio-related.

As for keylogging, I don't remember finding anything that looked like it could be recording keystrokes. I believe it does keep a short buffer of keystrokes for debouncing / NKRO but I didn't see anything that wrote that data to flash or sent it to the host via USB.

I'm not an expert on embedded system behavior, and I didn't get through auditing / reversing the _entire_ firmware image. I also didn't try reversing the Windows driver(s) at all. But the GK6X firmware itself doesn't worry me.
